### ISSUE TITLE
Any luck with sdxl based model?

### ISSUE THREAD

**Issue by jsg921019** [songrise/Artist#3]
First, Thank you for interesting work.
Have you tried using SDXL based models? I found traits of playgroundv2 in the code.
But i could not find any mentions in README or paper.

+ Also curious about experiments using image style reference instead of text style references.

**Comment by songrise** [comment]
Thanks for your comment.  1. Yes I am still trying to extend it to SDXL-based models. Currently I find Playground v2 works well for some image and prompts, but the performance is not as rubost as the SD2.1. So I did not include it in current version. 2.  The reference image based style transfer is another intereseting future work, which I also tried before (not included in this repo). 

This paper is still a WIP project, so I may update the two features latter depends on experiment results.

**Comment by jsg921019** [comment]
thank you for the answer!

**Comment by songrise** [comment]
added playground v2 config, you can try it out
