### ISSUE TITLE
Duplicated Package (Pillow) in requirements.txt

### ISSUE THREAD

**Issue by khaifahmi99** [songrise/Artist#4]
Hi, I tried running this repo locally and I noticed an issue during dependency installation. It appears that you specified 2 versions of the same library (Pillow).

https://github.com/songrise/Artist/blob/dcc252adb81e7e57e1763758cf57b8c865dbe1bb/requirements.txt#L8

**Comment by songrise** [comment]
the requirement is generated by pipreqs. Do you figure out which pillow version is good? I will delete the redundant one

**Comment by khaifahmi99** [comment]
@songrise I managed to get it working with the more recent version (10.4.0). Note that I did not test it with the other version
